### ISSUE TITLE
Duplicate code in SnackbarViewExtension.swift

### ISSUE THREAD

**Issue by gamble2020** [ZaniLuca/SwiftUISnackbar#1]
Hi I just noticed you have duplicate code in the view extension.

**Comment by zaniluca** [comment]
> Hi I just noticed you have duplicate code in the view extension.

Hi @gamble2020, actually that's not duplicated code. These are just 2 ways to add the snackbar to a view. One uses `Text` and the other one uses `String`, look at the `title`, and `text` props

```swift
    func snackbar(isShowing: Binding<Bool>, title: String, text: String? = nil, style: SnackbarStyle, actionText: String? = nil, ...) -> some View {
    ...
    }

    func snackbar(isShowing: Binding<Bool>, title: Text, text: Text? = nil, style: SnackbarStyle, actionText: String? = nil,  ...) -> some View {
    ...
    }
```
