### ISSUE TITLE
SnackBar Hides behind TabView

### ISSUE THREAD

**Issue by sangampokharel** [ZaniLuca/SwiftUISnackbar#5]
SomeView()
 .snackbar(isShowing: snackBarVisible, title: "Validation Error !", text: showMessage.wrappedValue, style: .custom(.red),actionText: "Dismiss") {
                changePasswordVM.hideSnackBar()
            }

**Comment by sangampokharel** [comment]
<img width="383" alt="Screenshot 2024-02-20 at 4 45 58 PM" src="https://github.com/zaniluca/SwiftUISnackbar/assets/34125397/ae0d954a-10ab-44fc-b894-664dcb4bffae">

The red one is the snacbar used !

**Comment by zaniluca** [comment]
@sangampokharel hi!
I think the issue might be in the z-depth. Have you tried adding a [`.zIndex(_:)`](https://developer.apple.com/documentation/swiftui/view/zindex(_:)) to the `TabBar` and set it to 0?

I had the same problem and this trick solved it for me, let me know

**Comment by zaniluca** [comment]
@sangampokharel I assume it worked! Feel free to re-open it otherwise
